### ISSUE TITLE
this.visible() is not a function

### ISSUE THREAD

**Issue by boolieman** [futurepress/epub.js#568]
When I was working with v0.3 i found an error in the range finding solution that there was a missing function of `this.visible()` Is there a sample of this in another branch, I really would love to use this functionality and can gladly resolve the issue if you want instead of spending all your time on it.

https://github.com/futurepress/epub.js/blob/v0.3/src/rendition.js#L588

**Comment by fchasen** [comment]
Fixed in `0.3.17`
